deep_rl_node:
  ros__parameters:
    log_dirname: "turtlebot3.log"
    # algorithm: "dqn"
    # algorithm: "ppo"
    turn:
      x: 3.5
      y: 4.0
    gain:
      d: 10.0
      target: 0.0
      linear: 5.0
      angular: 1.0